El siguiente programa python es muy intuitivo funciona de la siguiente forma:
una vez ejecutemos el fichero el programa procedera a pedirnos que escribamos el primer valor de la cuenta,
para ser más especificos dicho valor como es de suponer ha de ser un numero pero también admite que indroduzcamos una 
cuenta una vez definido el primer valor nos devolvera el valor actual del mismo si introducimos un 3 nos imprimira un 3
si introducimos 3+3-2 nos devolvera el resultado 4 dicho esto lo siguiente que nos pedira será el simbolo de la operación
a realizar y en el caso de que introduzcamos un valor no valido nos dará un error y nos indicará los simbolos que admite
posteriormente nos pedira el segundo valor numerico de la operación con el cúal debemos seguir el mismo procedimiento que con 
el primero y finalmente nos devolvera el resultado seguido de un bello mensaje
